
Привет, Юрий!

Меня зовут Ярослав П. и я буду проверять твой проект. Попробую помочь
сделать тебе его еще лучше!

Ниже ты найдешь мои комментарии - пожалуйста, не перемещай, не изменяй и
не удаляй их. Я буду использовать цветовую разметку:

Комментарий ревьюера: Так выделены самые важные замечания. Без их
отработки проект не будет принят.

Комментарий ревьюера: Так выделены небольшие замечания или советы.

Комментарий ревьюера: Так я выделяю все остальные комментарии.

Давай работать над проектом в диалоге: если ты что-то меняешь в проекте
или отвечаешь на мои комменатри — пиши об этом. Мне будет легче
отследить изменения, если ты выделишь свои комментарии:

Комментарий студента: Например, вот так.

Всё это поможет выполнить повторную проверку твоего проекта оперативнее.

== Обратная связь

* Проект отлично выполнен.
* Математическое доказательство и ответ на вопрос верные!

Проект принят, удачи в дальнейшем обучении!

Вам нужно защитить данные клиентов страховой компании «Хоть потоп».
Разработайте такой метод преобразования данных, чтобы по ним было сложно
восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей
машинного обучения не ухудшилось. Подбирать наилучшую модель не
требуется.

Комментарий ревьюера

Введение хорошее, однако было бы здорово добавить название проекта и
дать содержание/шаги проекта.

== 1. Загрузка данных


+*In[1]:*+
[source, ipython3]
----
#Загрузим данные и импортируем необходимые библиотеки
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import urllib.request
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error
data = pd.read_csv('/datasets/insurance.csv')
----


+*In[2]:*+
[source, ipython3]
----
#Просмотрим содержимое датасета и проанализируем его
data.head()
----


+*Out[2]:*+
----
[cols=",,,,,",options="header",]
|===
| |Пол |Возраст |Зарплата |Члены семьи |Страховые выплаты
|0 |1 |41.0 |49600.0 |1 |0
|1 |0 |46.0 |38000.0 |1 |1
|2 |0 |29.0 |21000.0 |0 |0
|3 |0 |21.0 |41700.0 |2 |0
|4 |1 |28.0 |26100.0 |0 |0
|===
----


+*In[3]:*+
[source, ipython3]
----
data.describe()
----


+*Out[3]:*+
----
[cols=",,,,,",options="header",]
|===
| |Пол |Возраст |Зарплата |Члены семьи |Страховые выплаты
|count |5000.000000 |5000.000000 |5000.000000 |5000.000000 |5000.000000
|mean |0.499000 |30.952800 |39916.360000 |1.194200 |0.148000
|std |0.500049 |8.440807 |9900.083569 |1.091387 |0.463183
|min |0.000000 |18.000000 |5300.000000 |0.000000 |0.000000
|25% |0.000000 |24.000000 |33300.000000 |0.000000 |0.000000
|50% |0.000000 |30.000000 |40200.000000 |1.000000 |0.000000
|75% |1.000000 |37.000000 |46600.000000 |2.000000 |0.000000
|max |1.000000 |65.000000 |79000.000000 |6.000000 |5.000000
|===
----


+*In[4]:*+
[source, ipython3]
----
data.info()
----


+*Out[4]:*+
----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
----

Вывод: данные чистые, можем работать с ними.

Комментарий ревьюера

Данные загружены, немного проанализированы - отлично. Это важно делать
даже в таком небольшом проекте.

== 2. Умножение матриц

В этом задании вы можете записывать формулы в _Jupyter Notebook._

Чтобы записать формулу внутри текста, окружите её символами доллара
\latexmath:[$; если снаружи — двойными символами \\$]\$. Эти формулы
записываются на языке вёрстки _LaTeX._

Для примера мы записали формулы линейной регрессии. Можете их
скопировать и отредактировать, чтобы решить задачу.

Работать в _LaTeX_ необязательно.

Обозначения:

* latexmath:[$X$] — матрица признаков (нулевой столбец состоит из
единиц)
* latexmath:[$y$] — вектор целевого признака
* latexmath:[$P$] — матрица, на которую умножаются признаки
* latexmath:[$w$] — вектор весов линейной регрессии (нулевой элемент
равен сдвигу)

Предсказания:

[latexmath]
++++
\[
a = Xw
\]
++++

Задача обучения:

[latexmath]
++++
\[
w = \arg\min_w MSE(Xw, y)
\]
++++

Формула обучения:

[latexmath]
++++
\[
w = (X^T X)^{-1} X^T y
\]
++++

*Ответ:* Нет, не изменится

*Обоснование:* Формула расчета весов для линейной регрессии:

[latexmath]
++++
\[
w = (X^T X)^{-1} X^T y
\]
++++
Представим новую матрицу признаков latexmath:[$X1$] как произведение
старой latexmath:[$X$] на матрицу latexmath:[$P$] (обратимую):

[latexmath]
++++
\[
X1 = X * P
\]
++++
Подставим новое значение X1 в формулу latexmath:[$w1$]:

[latexmath]
++++
\[
w1 = ((X P)^T X P)^{-1} (X P)^T y
\]
++++
Раскроем первое произведение $ (XP)^T $:

[latexmath]
++++
\[
w1 = (P^T X^T X P)^{-1} P^T X^T y
\]
++++
Перегруппируем множители в скобках, чтобы это выглядело как произведение
трех множителей:

[latexmath]
++++
\[
w1 = (P^T (X^T X) P)^{-1} P^T X^T y
\]
++++
Раскроем скобки $ (P^T (X^T X) P)^\{-1} $:

[latexmath]
++++
\[
w1 = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
\]
++++
Так как latexmath:[$P$] по условию обратимая, то произведение
latexmath:[$(P^T)^{-1} P^T$] равно latexmath:[$E$] (единичная матрица):

[latexmath]
++++
\[
w1 = P^{-1} (X^T X)^{-1} E X^T y = P^{-1} (X^T X)^{-1} X^T y
\]
++++
Можно заметить, что справа получилась формула для latexmath:[$w$]:

[latexmath]
++++
\[
w1 = P^{-1} (X^T X)^{-1} X^T y = P^{-1} w
\]
++++
Подставим новое значение весов 𝑤1 в формулу для предсказаний линейной
регрессии. Предсказания модели расчитываются по формуле:

[latexmath]
++++
\[
a = Xw
\]
++++
Подставим в эту формулу значения latexmath:[$X1$] и latexmath:[$w1$] для
того, чтобы на их основе вычислить предсказания модели latexmath:[$a1$]:

[latexmath]
++++
\[
a1 = X1w1 = XPP^{-1} w
\]
++++
Так как latexmath:[$P$] по условию обратимая, то произведение
latexmath:[$PP^{-1}$] снова равно latexmath:[$E$]:

[latexmath]
++++
\[
a1 = XPP^{-1} w = X E w = X w = a
\]
++++
Мы доказали, что предсказания latexmath:[$a1$] для матрицы признаков,
умноженных на обратимую матрицу latexmath:[$P$] равны предсказаниям
latexmath:[$a$]. Следовательно, отвечая на вопрос изменится ли качество
линейной регрессии при умножении признаков на обратимую матрицу - нет,
не изменится. В данном случае, параметры линейной регрессии в исходной
задаче latexmath:[$w$] и в преобразованной latexmath:[$w1$] связаны
следующим образом:

[latexmath]
++++
\[
w1 = P^{-1} w
\]
++++

Комментарий ревьюера

Ответ и математическое обоснование верные!

== 3. Алгоритм преобразования

*Алгоритм*

Алгоритм преобразования данных должен содержать процесс создания
обратимой матрицы latexmath:[$P$] и ее умножения на матрицу признаков.

Комментарий ревьюера

Здесь преполагается записать алгоритм в таком виде:

[arabic]
. Создадим…
. Проверим…
. Умножим… и т.д.

*Обоснование*


+*In[5]:*+
[source, ipython3]
----
random_matrix = np.random.randint(100,size = (4, 4))
random_matrix
----


+*Out[5]:*+
----array([[69, 98, 19, 67],
       [96, 78, 64,  4],
       [55, 35, 92, 81],
       [56,  6, 74, 76]])----


+*In[6]:*+
[source, ipython3]
----
#Проверка матрицы на обратимость
matrix_inverted = np.linalg.inv(random_matrix)
matrix_inverted
----


+*Out[6]:*+
----array([[ 0.00238628,  0.00866875, -0.03127601,  0.0307737 ],
       [ 0.00513109, -0.00014064,  0.01871053, -0.02445755],
       [-0.01032613,  0.00339863,  0.02423751, -0.01690767],
       [ 0.00789099, -0.00968559, -0.00203135,  0.00887612]])----

Комментарий ревьюера

Отлично, проверка на обратимость есть!


+*In[7]:*+
[source, ipython3]
----
#Обозначим признаки и целевой признак
features = data.drop('Страховые выплаты', axis = 1)
target = data['Страховые выплаты']
 
#Проведем масштабирование с помощью StandardScaler()
scaler = StandardScaler()
scaler.fit(features)

#Сохраним масштабированные признаки в features_scaled
features_scaled = scaler.transform(features)
----


+*In[8]:*+
[source, ipython3]
----
#Расчитаем веса $w$ для исходных признаков (масштабированных) по стандартной формуле $w = (X^T X)^{-1} X^T y$
w = np.linalg.inv(features_scaled.T.dot(features_scaled)).dot(features_scaled.T).dot(target)

#Расчитаем вектор предсказаний по исходным признакам по формуле 𝑎=𝑋𝑤
a = features_scaled @ w

#Проведем преобразование признаков:
features_scaled_p = features_scaled @ random_matrix

#Расчитаем веса  𝑤1  для преобразованных признаков по стандартной формуле  𝑤=(𝑋𝑇𝑋)−1𝑋𝑇𝑦
w1 = np.linalg.inv(features_scaled_p.T.dot(features_scaled_p)).dot(features_scaled_p.T).dot(target)

#Расчитаем вектор предсказаний по преобразованным признакам по формуле  𝑎=𝑋𝑤
a1 = features_scaled_p @ w1

#Получим вектор разниц между предсказаниями по исходным признакам  𝑎  и преобразованным  𝑎1 :
diff = a - a1

#Просуммируем все элементы вектора diff, чтобы убедиться, что расхождения минимальны.
diff.sum()
----


+*Out[8]:*+
-----2.8871002810682e-14----

Видим, что сумма расхождения маленькая. Это говорит о том что a=a1, что
доказывает, что преобразование не приводит к разным предсказаниям модели
и не ухудшает качество модели.

Я предложил алгоритм преобразования данных для решения задачи и
обосновал, почему качество линейной регрессии не поменяется.

== 4. Проверка алгоритма


+*In[9]:*+
[source, ipython3]
----

#Создадим модель линейной регрессии для исходных данных и посмотрим ее оценку R2_Score
model = LinearRegression(normalize = True)
model.fit(features, target)
predictions = model.predict(features)
mse = mean_squared_error(target, predictions)
print('MSE Score:', mse)
print('R2_Score на исходных данных: ',r2_score(target, predictions))
----


+*Out[9]:*+
----
MSE Score: 0.1233468894171086
R2_Score на исходных данных:  0.42494550286668
----


+*In[10]:*+
[source, ipython3]
----

#Преобразуем признаки умножив на матрицу P и рассчитаем R2_Score
features_matrix = features_scaled @ random_matrix
model.fit(features_matrix, target)
predictions_matrix = model.predict(features_matrix)
mse = mean_squared_error(target, predictions)
print('MSE Score:', mse)
print('R2_Score для преобразованных  признаков: ',r2_score(target, predictions_matrix))
----


+*Out[10]:*+
----
MSE Score: 0.1233468894171086
R2_Score для преобразованных  признаков:  0.4249455028666801
----

Как видим, R2_score равен и в исходных давнных и в преобразованных.
Данные защищенны, а качество модели не ухудшилось.

Комментарий ревьюера

Результат подтвержден как математически, так и экспериментально,
здорово.

== Чек-лист проверки

Поставьте `x' в выполненных пунктах. Далее нажмите Shift+Enter.

* ☒ Jupyter Notebook открыт
* ☒ Весь код выполняется без ошибок
* ☒ Ячейки с кодом расположены в порядке исполнения
* ☒ Выполнен шаг 1: данные загружены
* ☒ Выполнен шаг 2: получен ответ на вопрос об умножении матриц
** ☒ Указан правильный вариант ответа
** ☒ Вариант обоснован
* ☒ Выполнен шаг 3: предложен алгоритм преобразования
** ☒ Алгоритм описан
** ☒ Алгоритм обоснован
* ☒ Выполнен шаг 4: алгоритм проверен
** ☒ Алгоритм реализован
** ☒ Проведено сравнение качества моделей до и после преобразования
